package m68k

import "testing"

func TestDecodeFirstVerticalSlice(t *testing.T) {
	tests := []struct {
		opcode uint16
		want   Decoded
	}{
		{0x4e71, Decoded{Instruction: InstructionNOP}},
		{0x46fc, Decoded{Instruction: InstructionMOVEImmediateToSR}},
		{0x23fc, Decoded{Instruction: InstructionMOVELongImmediateToAbsoluteLong}},
		{0x4eb8, Decoded{Instruction: InstructionJSRAbsoluteWord}},
		{0x207c, Decoded{Instruction: InstructionMOVEAImmediateLong, Register: 0}},
		{0x2e7c, Decoded{Instruction: InstructionMOVEAImmediateLong, Register: 7}},
		{0x3039, Decoded{Instruction: InstructionMOVEWordAbsoluteLongToData, Register: 0}},
		{0x3e39, Decoded{Instruction: InstructionMOVEWordAbsoluteLongToData, Register: 7}},
		{0x33c0, Decoded{Instruction: InstructionMOVEWordDataToAbsoluteLong, Register: 0}},
		{0x33c7, Decoded{Instruction: InstructionMOVEWordDataToAbsoluteLong, Register: 7}},
		{0x0240, Decoded{Instruction: InstructionANDIWordData, Register: 0}},
		{0x0247, Decoded{Instruction: InstructionANDIWordData, Register: 7}},
		{0x303c, Decoded{Instruction: InstructionMOVEWordImmediateToData, Register: 0}},
		{0x3e3c, Decoded{Instruction: InstructionMOVEWordImmediateToData, Register: 7}},
		{0x3200, Decoded{Instruction: InstructionMOVEWordDataToData, Register: 1, SourceRegister: 0}},
		{0x3e07, Decoded{Instruction: InstructionMOVEWordDataToData, Register: 7, SourceRegister: 7}},
		{0x1080, Decoded{Instruction: InstructionMOVEByteDataToAddressIndirect, Register: 0, SourceRegister: 0}},
		{0x1e87, Decoded{Instruction: InstructionMOVEByteDataToAddressIndirect, Register: 7, SourceRegister: 7}},
		{0x14d1, Decoded{Instruction: InstructionMOVEByteAddressIndirectToPostincrement, Register: 2, SourceRegister: 1}},
		{0x1ed7, Decoded{Instruction: InstructionMOVEByteAddressIndirectToPostincrement, Register: 7, SourceRegister: 7}},
		{0x33fc, Decoded{Instruction: InstructionMOVEWordImmediateToAbsoluteLong}},
		{0x0c40, Decoded{Instruction: InstructionCMPIWordData, Register: 0}},
		{0x0c47, Decoded{Instruction: InstructionCMPIWordData, Register: 7}},
		{0x0c79, Decoded{Instruction: InstructionCMPIWordAbsoluteLong}},
		{0x50c8, Decoded{Instruction: InstructionDBcc, Register: 0, Condition: 0}},
		{0x5fcf, Decoded{Instruction: InstructionDBcc, Register: 7, Condition: 15}},
		{0xb011, Decoded{Instruction: InstructionCMPByteAddressIndirectToData, Register: 0, SourceRegister: 1}},
		{0xbe17, Decoded{Instruction: InstructionCMPByteAddressIndirectToData, Register: 7, SourceRegister: 7}},
		{0x12a2, Decoded{Instruction: InstructionMOVEBytePredecrementToAddressIndirect, Register: 1, SourceRegister: 2}},
		{0x4244, Decoded{Instruction: InstructionCLRWordData, Register: 4}},
		{0x4279, Decoded{Instruction: InstructionCLRWordAbsoluteLong}},
		{0x4239, Decoded{Instruction: InstructionCLRByteAbsoluteLong}},
		{0xd822, Decoded{Instruction: InstructionADDBytePredecrementToData, Register: 4, SourceRegister: 2}},
		{0x9a1a, Decoded{Instruction: InstructionSUBBytePostincrementFromData, Register: 5, SourceRegister: 2}},
		{0xdc62, Decoded{Instruction: InstructionADDWordPredecrementToData, Register: 6, SourceRegister: 2}},
		{0x9e5a, Decoded{Instruction: InstructionSUBWordPostincrementFromData, Register: 7, SourceRegister: 2}},
		{0x0c62, Decoded{Instruction: InstructionCMPIWordPredecrement, Register: 2}},
		{0x5d8a, Decoded{Instruction: InstructionSUBQLongAddress, Register: 2, Quick: 6}},
		{0xb822, Decoded{Instruction: InstructionCMPBytePredecrementToData, Register: 4, SourceRegister: 2}},
		{0x13fc, Decoded{Instruction: InstructionMOVEByteImmediateToAbsoluteLong}},
		{0xb94b, Decoded{Instruction: InstructionCMPMWord, Register: 4, SourceRegister: 3}},
		{0x2a4c, Decoded{Instruction: InstructionMOVEAAddressToAddress, Register: 5, SourceRegister: 4}},
		{0xdafc, Decoded{Instruction: InstructionADDAWordImmediate, Register: 5}},
		{0xd1fc, Decoded{Instruction: InstructionADDALongImmediate, Register: 0}},
		{0xd9c2, Decoded{Instruction: InstructionADDALongData, Register: 4, SourceRegister: 2}},
		{0x4843, Decoded{Instruction: InstructionSWAP, Register: 3}},
		{0x4284, Decoded{Instruction: InstructionCLRLongData, Register: 4}},
		{0x4203, Decoded{Instruction: InstructionCLRByteData, Register: 3}},
		{0x5206, Decoded{Instruction: InstructionADDQByteData, Register: 6, Quick: 1}},
		{0x5239, Decoded{Instruction: InstructionADDQByteAbsoluteLong, Quick: 1}},
		{0x5279, Decoded{Instruction: InstructionADDQWordAbsoluteLong, Quick: 1}},
		{0x4e73, Decoded{Instruction: InstructionRTE}},
		{0x0706, Decoded{Instruction: InstructionBTSTDataData, Register: 6, SourceRegister: 3}},
		{0x4442, Decoded{Instruction: InstructionNEGWordData, Register: 2}},
		{0xc5db, Decoded{Instruction: InstructionMULSWordPostincrement, Register: 2, SourceRegister: 3}},
		{0x5301, Decoded{Instruction: InstructionSUBQByteData, Register: 1, Quick: 1}},
		{0xd882, Decoded{Instruction: InstructionADDLongDataToData, Register: 4, SourceRegister: 2}},
		{0xd701, Decoded{Instruction: InstructionADDXByteData, Register: 3, SourceRegister: 1}},
		{0x0200, Decoded{Instruction: InstructionANDIByteData, Register: 0}},
		{0xb61c, Decoded{Instruction: InstructionCMPBytePostincrementToData, Register: 3, SourceRegister: 4}},
		{0xb89d, Decoded{Instruction: InstructionCMPLongPostincrementToData, Register: 4, SourceRegister: 5}},
		{0x3f3c, Decoded{Instruction: InstructionMOVEWordImmediateToPredecrement, Register: 7}},
		{0x4ef9, Decoded{Instruction: InstructionJMPAbsoluteLong}},
		{0x0040, Decoded{Instruction: InstructionORIWordData, Register: 0}},
		{0x0079, Decoded{Instruction: InstructionORIWordAbsoluteLong}},
		{0x13c5, Decoded{Instruction: InstructionMOVEByteDataToAbsoluteLong, Register: 5}},
		{0x4a13, Decoded{Instruction: InstructionTSTByteAddressIndirect, Register: 3}},
		{0x4a41, Decoded{Instruction: InstructionTSTWordData, Register: 1}},
		{0x4a39, Decoded{Instruction: InstructionTSTByteAbsoluteLong}},
		{0xbf46, Decoded{Instruction: InstructionEORWordDataToData, Register: 6, SourceRegister: 7}},
		{0x4647, Decoded{Instruction: InstructionNOTWordData, Register: 7}},
		{0xcc47, Decoded{Instruction: InstructionANDWordDataToData, Register: 6, SourceRegister: 7}},
		{0x163c, Decoded{Instruction: InstructionMOVEByteImmediateToData, Register: 3}},
		{0x0285, Decoded{Instruction: InstructionANDILongData, Register: 5}},
		{0x263c, Decoded{Instruction: InstructionMOVELongImmediateToData, Register: 3}},
		{0x8280, Decoded{Instruction: InstructionORLongDataToData, Register: 1, SourceRegister: 0}},
		{0xc6fc, Decoded{Instruction: InstructionMULUWordImmediate, Register: 3}},
		{0x5889, Decoded{Instruction: InstructionADDQAddress, Register: 1, Quick: 4}},
		{0x369d, Decoded{Instruction: InstructionMOVEWordPostincrementToAddressIndirect, Register: 3, SourceRegister: 5}},
		{0x375d, Decoded{Instruction: InstructionMOVEWordPostincrementToDisplacement, Register: 3, SourceRegister: 5}},
		{0x36bc, Decoded{Instruction: InstructionMOVEWordImmediateToAddressIndirect, Register: 3}},
		{0x377c, Decoded{Instruction: InstructionMOVEWordImmediateToDisplacement, Register: 3}},
		{0x277c, Decoded{Instruction: InstructionMOVELongImmediateToDisplacement, Register: 3}},
		{0x5339, Decoded{Instruction: InstructionSUBQByteAbsoluteLong, Quick: 1}},
		{0x2679, Decoded{Instruction: InstructionMOVEALongAbsoluteLong, Register: 3}},
		{0x13eb, Decoded{Instruction: InstructionMOVEByteDisplacementToAbsoluteLong, SourceRegister: 3}},
		{0x0c93, Decoded{Instruction: InstructionCMPILongAddressIndirect, Register: 3}},
		{0x322b, Decoded{Instruction: InstructionMOVEWordDisplacementToData, Register: 1, SourceRegister: 3}},
		{0x142b, Decoded{Instruction: InstructionMOVEByteDisplacementToData, Register: 2, SourceRegister: 3}},
		{0xd579, Decoded{Instruction: InstructionADDWordDataToAbsoluteLong, SourceRegister: 2}},
		{0x5cb9, Decoded{Instruction: InstructionADDQLongAbsoluteLong, Quick: 6}},
		{0x0805, Decoded{Instruction: InstructionBTSTImmediateData, Register: 5}},
		{0x1e39, Decoded{Instruction: InstructionMOVEByteAbsoluteLongToData, Register: 7}},
		{0xbe39, Decoded{Instruction: InstructionCMPByteAbsoluteLongToData, Register: 7}},
		{0xb279, Decoded{Instruction: InstructionCMPWordAbsoluteLongToData, Register: 1}},
		{0x95ce, Decoded{Instruction: InstructionSUBALongAddress, Register: 2, SourceRegister: 6}},
		{0x3011, Decoded{Instruction: InstructionMOVEWordAddressIndirectToData, Register: 0, SourceRegister: 1}},
		{0x341a, Decoded{Instruction: InstructionMOVEWordPostincrementToData, Register: 2, SourceRegister: 2}},
		{0x3280, Decoded{Instruction: InstructionMOVEWordDataToAddressIndirect, Register: 1, SourceRegister: 0}},
		{0x2e78, Decoded{Instruction: InstructionMOVEAAbsoluteWord, Register: 7}},
		{0x4ed0, Decoded{Instruction: InstructionJMPAddressIndirect, Register: 0}},
		{0x4eb9, Decoded{Instruction: InstructionJSRAbsoluteLong}},
		{0x7000, Decoded{Instruction: InstructionMOVEQ, Register: 0, Immediate8: 0}},
		{0x76ff, Decoded{Instruction: InstructionMOVEQ, Register: 3, Immediate8: 0xff}},
		{0x6002, Decoded{Instruction: InstructionBRA, Immediate8: 2}},
		{0x6100, Decoded{Instruction: InstructionBSR, Condition: 1}},
		{0x66fe, Decoded{Instruction: InstructionBcc, Condition: 6, Immediate8: 0xfe}},
		{0x48e7, Decoded{Instruction: InstructionMOVEMLongRegistersToPredecrement, Register: 7}},
		{0x4cdf, Decoded{Instruction: InstructionMOVEMLongPostincrementToRegisters, Register: 7}},
		{0x4e75, Decoded{Instruction: InstructionRTS}},
		{0x327c, Decoded{Instruction: InstructionMOVEAWordImmediate, Register: 1}},
		{0x487a, Decoded{Instruction: InstructionPEAPCDisplacement}},
		{0x2f3c, Decoded{Instruction: InstructionMOVELongImmediateToPredecrement, Register: 7}},
		{0x2f0d, Decoded{Instruction: InstructionMOVELongAddressToPredecrement, Register: 7, SourceRegister: 5}},
		{0x41fa, Decoded{Instruction: InstructionLEAPCDisplacement, Register: 0}},
		{0x2ad8, Decoded{Instruction: InstructionMOVELongPostincrementToPostincrement, Register: 5, SourceRegister: 0}},
		{0xe319, Decoded{Instruction: InstructionROLByteImmediate, Register: 1, Quick: 1}},
		{0x3e3b, Decoded{Instruction: InstructionMOVEWordPCIndexedToData, Register: 7}},
		{0x4eb3, Decoded{Instruction: InstructionJSRAddressIndexed, Register: 3}},
		{0x0c39, Decoded{Instruction: InstructionCMPIByteAbsoluteLong}},
		{0x4299, Decoded{Instruction: InstructionCLRLongPostincrement, Register: 1}},
		{0x4219, Decoded{Instruction: InstructionCLRBytePostincrement, Register: 1}},
		{0x22fc, Decoded{Instruction: InstructionMOVELongImmediateToPostincrement, Register: 1}},
		{0x425a, Decoded{Instruction: InstructionCLRWordPostincrement, Register: 2}},
		{0x0483, Decoded{Instruction: InstructionSUBILongData, Register: 3}},
		{0x4a79, Decoded{Instruction: InstructionTSTWordAbsoluteLong}},
		{0x23c4, Decoded{Instruction: InstructionMOVELongDataToAbsoluteLong, Register: 4}},
		{0x23c8, Decoded{Instruction: InstructionMOVELongAddressToAbsoluteLong, Register: 0}},
		{0x3942, Decoded{Instruction: InstructionMOVEWordDataToDisplacement, Register: 4, SourceRegister: 2}},
		{0x2943, Decoded{Instruction: InstructionMOVELongDataToDisplacement, Register: 4, SourceRegister: 3}},
		{0x48c6, Decoded{Instruction: InstructionEXTLongData, Register: 6}},
		{0x9447, Decoded{Instruction: InstructionSUBWordDataFromData, Register: 2, SourceRegister: 7}},
		{0xc4c1, Decoded{Instruction: InstructionMULUWordData, Register: 2, SourceRegister: 1}},
		{0x84c1, Decoded{Instruction: InstructionDIVUWordData, Register: 2, SourceRegister: 1}},
		{0x3302, Decoded{Instruction: InstructionMOVEWordDataToPredecrement, Register: 1, SourceRegister: 2}},
		{0xef8b, Decoded{Instruction: InstructionLSLLongImmediate, Register: 3, Quick: 7}},
		{0x2503, Decoded{Instruction: InstructionMOVELongDataToPredecrement, Register: 2, SourceRegister: 3}},
		{0x4251, Decoded{Instruction: InstructionCLRWordAddressIndirect, Register: 1}},
		{0x42a2, Decoded{Instruction: InstructionCLRLongPredecrement, Register: 2}},
		{0xffff, Decoded{Instruction: InstructionIllegal}},
	}
	for _, test := range tests {
		if got := Decode(test.opcode); got != test.want {
			t.Errorf("Decode($%04X) = %+v, want %+v", test.opcode, got, test.want)
		}
	}
}

func TestConditionsExhaustiveAgainstBooleanDefinitions(t *testing.T) {
	for flags := uint16(0); flags < 16; flags++ {
		c := flags&flagCarry != 0
		v := flags&flagOverflow != 0
		z := flags&flagZero != 0
		n := flags&flagNegative != 0
		want := [16]bool{
			true, false, !c && !z, c || z,
			!c, c, !z, z,
			!v, v, !n, n,
			n == v, n != v, !z && n == v, z || n != v,
		}
		for condition := uint8(0); condition < 16; condition++ {
			if got := conditionTrue(condition, flags); got != want[condition] {
				t.Errorf("condition %d flags $%X = %v, want %v", condition, flags, got, want[condition])
			}
		}
	}
}
