package ui

// Strings 是介面上所有可見文字。用結構而不是 map，少一個 key 會在編譯期就發現，
// 不會變成畫面上的空白。欄位順序即原始的宣告順序。
type Strings struct {
	Resume               string
	SaveState            string
	LoadState            string
	ResetMachine         string
	Cheats               string
	Settings             string
	Diagnostics          string
	Screenshot           string
	EjectCart            string
	Quit                 string
	Paused               string
	NoCartridge          string
	SlotPrefix           string
	Back                 string
	ModeSave             string
	ModeLoad             string
	SlotsTitle           string
	EmptySlot            string
	SlotLegend           string
	SlotKeys             string
	Cancel               string
	Overwrite            string
	Delete               string
	DismissError         string
	SoftReset            string
	ColdReset            string
	NotYet               string
	StageCheats          string
	StageSettings        string
	StageDiag            string
	Saved                string
	Loaded               string
	Deleted              string
	SlotEmpty            string
	SlotRejected         string
	OverwriteAsk         string
	OverwriteWhy         string
	DeleteAsk            string
	DeleteWhy            string
	QuitAsk              string
	QuitWhy              string
	ScreenshotHK         string
	AppTitle             string
	SectionFirmware      string
	SectionRecent        string
	FirmwareIPL          string
	FirmwareKey          string
	FirmwareSoundA       string
	FirmwareSoundB       string
	FirmwareLoaded       string
	FirmwareMissing      string
	FirmwareUnset        string
	FirmwareKnown        string
	FirmwareUnlisted     string
	FirmwareSetUp        string
	FirmwareTitle        string
	FirmwareNotice       string
	FirmwareIncompl      string
	ChooseCartridge      string
	About                string
	AboutTitle           string
	AboutName            string
	AboutDisclaimer      string
	AboutThirdParty      string
	AboutMAME            string
	CGOEnabled           string
	CGODisabled          string
	BrowserTitle         string
	BrowserNoPreview     string
	BrowserEmpty         string
	FieldSize            string
	FieldKind            string
	FieldSHA             string
	FieldSaves           string
	FieldBattery         string
	FieldCompat          string
	CompatVerified       string
	CompatUnverified     string
	LoadCartridge        string
	BrowserKeys          string
	MissingFile          string
	StatusNoCartridge    string
	StatusReady          string
	HaltTitle            string
	HaltBody             string
	HaltFrame            string
	HaltInstructions     string
	HaltCartridge        string
	HaltIPL              string
	None                 string
	EjectToShell         string
	SettingsTitle        string
	SettingsInput        string
	SettingsHotkeys      string
	SettingsVideo        string
	SettingsAudio        string
	SettingsLanguage     string
	StageVideo           string
	StageAudio           string
	StageLanguage        string
	InputTitle           string
	HotkeyTitle          string
	ColumnButton         string
	ColumnAction         string
	ColumnKeyboard       string
	ColumnGamepad        string
	PressInput           string
	ConflictWith         string
	InputHelp            string
	HotkeyHelp           string
	HotkeyConflict       string
	On                   string
	Off                  string
	VideoTitle           string
	AudioTitle           string
	DiagTitle            string
	VideoScale           string
	VideoInteger         string
	VideoAspect          string
	VideoFilter          string
	VideoFullscreen      string
	VideoFrameBlend      string
	VideoShowFPS         string
	VideoSuppress        string
	VideoSuppressNote    string
	VideoApertureNote    string
	StageFrameBlend      string
	AudioVolume          string
	AudioMuteFast        string
	AudioBuffer          string
	AudioBufferNote      string
	AudioSink            string
	AudioFormat          string
	AudioFormatValue     string
	AudioBufferState     string
	AudioUnderrun        string
	AudioNote            string
	AudioNoSink          string
	DiagFrame            string
	DiagM68K             string
	DiagM65C02           string
	DiagIRQ7             string
	DiagIRQ45            string
	DiagClash            string
	DiagFrontend         string
	DiagCGO              string
	DiagLayerMask        string
	DiagLayerNote        string
	DiagMaskWarning      string
	LayerTilemap0        string
	LayerTilemap1        string
	LayerTilemap2        string
	LayerSprite          string
	LayerROZ             string
	LayerWindow          string
	CheatTitle           string
	CheatRange           string
	CheatRangeValue      string
	CheatWidth           string
	CheatCompare         string
	CheatValue           string
	CheatNewSearch       string
	CheatRefine          string
	CheatClear           string
	CheatCandidates      string
	CheatRefines         string
	CheatPrevious        string
	CheatTruncNote       string
	CheatEnable          string
	CheatEnableHint      string
	CheatColumnLock      string
	CheatColumnName      string
	CheatColumnAddress   string
	CheatColumnWidth     string
	CheatColumnValue     string
	CheatColumnFormat    string
	CheatEmpty           string
	CheatLockNote        string
	CheatEvidenceWarning string
	CheatActive          string
	CheatMarker          string
	MenuHint             string
	CaptureStart         string
	CaptureStop          string
	CaptureHK            string
	CaptureFrames        string
	CaptureStarted       string
	CaptureStopped       string
	ScreenshotSaved      string
	TouchTitle string
	TouchOpacity string
	TouchScale string
	TouchDeadzone string
	TouchDeadzoneNote string
	TouchSwapHands string
	TouchStickMode string
	StageStickMode string
	TouchHaptics string
	TouchNote string

	HotkeyToast string
	HotkeyResumed string
	HotkeyFastForward string
	HotkeyMute string
	HotkeySlot string
}
