package ui

// P1 用到的文案。多語言在 P8 才做，屆時這些常數換成查表，呼叫點不變。
const (
	textResume        = "繼續遊戲"
	textSaveState     = "存檔"
	textLoadState     = "讀檔"
	textResetMachine  = "重設主機"
	textCheats        = "金手指"
	textSettings      = "設定"
	textDiagnostics   = "診斷"
	textScreenshot    = "截圖"
	textEjectCart     = "退出卡帶"
	textQuit          = "離開模擬器"
	textPaused        = "已暫停"
	textNoCartridge   = "未載入卡帶"
	textSlotPrefix    = "槽 "
	textBack          = "‹ 返回"
	textModeSave      = "存檔"
	textModeLoad      = "讀檔"
	textSlotsTitle    = "存檔槽"
	textEmptySlot     = "（空）"
	textSlotLegend    = "✔ 可讀取   ✖ 已拒絕（載入前驗證失敗，現行狀態不會被更動）"
	textSlotKeys      = "Enter 執行 · Del 刪除 · ←→↑↓ 選擇"
	textCancel        = "取消"
	textOverwrite     = "覆寫"
	textDelete        = "刪除"
	textDismissError  = "Enter 關閉"
	textSoftReset     = "軟重設"
	textColdReset     = "冷開機"
	textNotYet        = "這一項還沒做：%s"
	textStageCheats   = "金手指在 P6"
	textStageSettings = "設定在 P3 與 P5"
	textStageDiag     = "診斷在 P5"
	textSaved         = "已寫入存檔槽 %d。"
	textLoaded        = "已讀取存檔槽 %d。"
	textDeleted       = "已刪除存檔槽 %d。"
	textSlotEmpty     = "存檔槽 %d 是空的。"
	textSlotRejected  = "存檔槽 %d 無法讀取：%s"
	textOverwriteAsk  = "覆寫存檔槽 %d？"
	textOverwriteWhy  = "槽 %d 目前是 %s 的存檔，frame %d。覆寫後無法復原。"
	textDeleteAsk     = "刪除存檔槽 %d？"
	textDeleteWhy     = "槽 %d 的 %s 存檔會被刪除，無法復原。"
	textQuitAsk       = "離開模擬器？"
	textQuitWhy       = "卡帶電池記憶體會先寫回再結束。"
	textScreenshotHK  = "F8"
)

// P2 的文案。
const (
	textAppTitle          = "SUPER A'CAN"
	textSectionFirmware   = "主機韌體"
	textSectionRecent     = "最近的卡帶"
	textFirmwareIPL       = "IPL"
	textFirmwareKey       = "UMC6650 key"
	textFirmwareSoundA    = "音效 BIOS 1"
	textFirmwareSoundB    = "音效 BIOS 2"
	textFirmwareLoaded    = "已載入"
	textFirmwareMissing   = "缺少"
	textFirmwareUnset     = "未設定"
	textFirmwareKnown     = "✔ 已知"
	textFirmwareUnlisted  = "未列於已驗證清單"
	textFirmwareSetUp     = "設定主機韌體…"
	textFirmwareTitle     = "主機韌體"
	textFirmwareNotice    = "這四個檔案由使用者自行提供，不隨本程式散布。"
	textFirmwareIncompl   = "韌體不齊：缺少任一檔案時不會啟動任何卡帶。"
	textChooseCartridge   = "選擇卡帶…"
	textAbout             = "關於"
	textAboutTitle        = "關於"
	textAboutName         = "Super A'Can 模擬器"
	textAboutDisclaimer   = "本程式不含、也不散布任何 ROM、BIOS 或遊戲畫面。所有卡帶與韌體檔案由使用者自行提供。"
	textAboutThirdParty   = "第三方元件"
	textAboutMAME         = "部分裝置行為參考 MAME（BSD-3-Clause），標示見原始碼註解。"
	textCGOEnabled        = "cgo 啟用"
	textCGODisabled       = "cgo 停用"
	textBrowserTitle      = "卡帶"
	textBrowserNoPreview  = "（無預覽：本程式不散布遊戲畫面）"
	textBrowserEmpty      = "這個目錄沒有卡帶檔案。"
	textFieldSize         = "大小"
	textFieldKind         = "類型"
	textFieldSHA          = "SHA-256"
	textFieldSaves        = "存檔"
	textFieldBattery      = "電池"
	textFieldCompat       = "相容性"
	textCompatVerified    = "1200 幀已驗證"
	textCompatUnverified  = "未驗證"
	textLoadCartridge     = "載入"
	textBrowserKeys       = "Enter 載入 · ↑↓ 選擇 · Esc 返回"
	textMissingFile       = "(檔案已移動或刪除)"
	textStatusNoCartridge = "尚未載入卡帶。先完成主機韌體設定，再選擇卡帶。"
	textStatusReady       = "韌體齊備。選擇一個卡帶開始。"
	textHaltTitle         = "✖ 已停止"
	textHaltBody          = "執行沒有繼續，機器狀態保留供檢視。"
	textHaltFrame         = "frame"
	textHaltInstructions  = "68000 指令"
	textHaltCartridge     = "卡帶"
	textHaltIPL           = "IPL"
	textNone              = "—"
	textEjectToShell      = "退出卡帶"
)

// P3 的文案。
const (
	textSettingsTitle    = "設定"
	textSettingsInput    = "輸入"
	textSettingsHotkeys  = "熱鍵"
	textSettingsVideo    = "影像"
	textSettingsAudio    = "音訊"
	textSettingsLanguage = "語言"
	textStageVideo       = "影像設定在 P5"
	textStageAudio       = "音訊設定在 P5"
	textStageLanguage    = "語言在 P8"
	textInputTitle       = "輸入"
	textHotkeyTitle      = "熱鍵"
	textColumnButton     = "按鈕"
	textColumnAction     = "動作"
	textColumnKeyboard   = "鍵盤"
	textColumnGamepad    = "手把"
	textPressInput       = "按下按鍵…（Esc 取消）"
	textConflictWith     = "與「%s」共用"
	textInputHelp        = "Enter 指定 · Del 清除 · ←→ 切換鍵盤／手把 · Tab 切換 P1／P2"
	textHotkeyHelp       = "Enter 指定 · Del 清除 · Esc 返回"
	textHotkeyConflict   = "※ 有熱鍵指到同一個按鍵，兩個動作都會觸發。"
)

// P5 的文案。
const (
	textOn                = "開啟"
	textOff               = "關閉"
	textVideoTitle        = "影像"
	textAudioTitle        = "音訊"
	textDiagTitle         = "診斷"
	textVideoScale        = "縮放"
	textVideoInteger      = "整數縮放"
	textVideoAspect       = "長寬比"
	textVideoFilter       = "濾鏡"
	textVideoFullscreen   = "全螢幕"
	textVideoFrameBlend   = "動態平滑"
	textVideoShowFPS      = "顯示 FPS"
	textVideoSuppress     = "抑制操作訊息"
	textVideoSuppressNote = "錯誤訊息不受此設定影響"
	textVideoApertureNote = "256 欄模式的卡帶在「1:1 像素」下畫面較窄，這是顯示孔徑造成的。"
	textStageFrameBlend   = "動態平滑尚未實作"
	textAudioVolume       = "主音量"
	textAudioMuteFast     = "全速時靜音"
	textAudioBuffer       = "輸出緩衝"
	textAudioBufferNote   = "溢位時丟棄最舊樣本"
	textAudioSink         = "輸出方式"
	textAudioFormat       = "取樣率"
	textAudioFormatValue  = "48,000 Hz · 16-bit · stereo"
	textAudioBufferState  = "緩衝狀態"
	textAudioUnderrun     = "underrun"
	textAudioNote         = "音量與緩衝只影響主機播放，不改變 UM6619 的取樣或機器時序。"
	textAudioNoSink       = "未設定（本前端沒有內建播放器）"
	textDiagFrame         = "frame"
	textDiagM68K          = "68000 指令"
	textDiagM65C02        = "65C02 指令"
	textDiagIRQ7          = "vblank IRQ7 受理"
	textDiagIRQ45         = "IRQ4 / IRQ5"
	textDiagClash         = "sound clash"
	textDiagFrontend      = "前端"
	textDiagCGO           = "cgo"
	textDiagLayerMask     = "圖層遮罩"
	textDiagLayerNote     = "圖層遮罩只影響 framebuffer 合成，不影響指令數與硬體時序。"
	textDiagMaskWarning   = "套了遮罩的畫面雜湊不可拿來對帳。"
	textLayerTilemap0     = "tilemap0"
	textLayerTilemap1     = "tilemap1"
	textLayerTilemap2     = "tilemap2"
	textLayerSprite       = "sprite"
	textLayerROZ          = "ROZ"
	textLayerWindow       = "window"
)

// P6 的文案。
const (
	textCheatTitle           = "金手指"
	textCheatRange           = "範圍"
	textCheatRangeValue      = "Work RAM $FC0000–$FCFFFF（64 KiB，固定）"
	textCheatWidth           = "寬度"
	textCheatCompare         = "比較"
	textCheatValue           = "數值"
	textCheatNewSearch       = "開始新搜尋"
	textCheatRefine          = "縮小範圍"
	textCheatClear           = "清除"
	textCheatCandidates      = "候選位址：%d（顯示 %d）"
	textCheatRefines         = " · 第 %d 次縮小 · 快照取自 frame 邊界"
	textCheatPrevious        = "前次 %d"
	textCheatTruncNote       = "候選超過 4096 時只顯示前 4096 筆；請再縮小一次範圍。"
	textCheatEnable          = "啟用金手指"
	textCheatEnableHint      = "X 切換 · Tab 切到搜尋"
	textCheatColumnLock      = "鎖"
	textCheatColumnName      = "名稱"
	textCheatColumnAddress   = "位址"
	textCheatColumnWidth     = "寬度"
	textCheatColumnValue     = "值"
	textCheatColumnFormat    = "格式"
	textCheatEmpty           = "清單是空的。到搜尋頁找出位址再加入。"
	textCheatLockNote        = "鎖定項在每個 frame 邊界寫入一次 Work RAM。"
	textCheatEvidenceWarning = "啟用期間的指令數與畫面雜湊不可作為硬體證據。"
	textCheatActive          = "※ 已啟用記憶體寫入"
	textCheatMarker          = "CHEAT"
)
