package ui

// P1 用到的文案。多語言在 P8 才做，屆時這些常數換成查表，呼叫點不變。
const (
	textResume        = "繼續遊戲"
	textSaveState     = "存檔"
	textLoadState     = "讀檔"
	textResetMachine  = "重設主機"
	textCheats        = "金手指"
	textSettings      = "設定"
	textDiagnostics   = "診斷"
	textScreenshot    = "截圖"
	textEjectCart     = "退出卡帶"
	textQuit          = "離開模擬器"
	textPaused        = "已暫停"
	textNoCartridge   = "未載入卡帶"
	textSlotPrefix    = "槽 "
	textBack          = "‹ 返回"
	textModeSave      = "存檔"
	textModeLoad      = "讀檔"
	textSlotsTitle    = "存檔槽"
	textEmptySlot     = "（空）"
	textSlotLegend    = "✔ 可讀取   ✖ 已拒絕（載入前驗證失敗，現行狀態不會被更動）"
	textSlotKeys      = "Enter 執行 · Del 刪除 · ←→↑↓ 選擇"
	textCancel        = "取消"
	textOverwrite     = "覆寫"
	textDelete        = "刪除"
	textDismissError  = "Enter 關閉"
	textSoftReset     = "軟重設"
	textColdReset     = "冷開機"
	textNotYet        = "這一項還沒做：%s"
	textStageCheats   = "金手指在 P6"
	textStageSettings = "設定在 P3 與 P5"
	textStageDiag     = "診斷在 P5"
	textSaved         = "已寫入存檔槽 %d。"
	textLoaded        = "已讀取存檔槽 %d。"
	textDeleted       = "已刪除存檔槽 %d。"
	textSlotEmpty     = "存檔槽 %d 是空的。"
	textSlotRejected  = "存檔槽 %d 無法讀取：%s"
	textOverwriteAsk  = "覆寫存檔槽 %d？"
	textOverwriteWhy  = "槽 %d 目前是 %s 的存檔，frame %d。覆寫後無法復原。"
	textDeleteAsk     = "刪除存檔槽 %d？"
	textDeleteWhy     = "槽 %d 的 %s 存檔會被刪除，無法復原。"
	textQuitAsk       = "離開模擬器？"
	textQuitWhy       = "卡帶電池記憶體會先寫回再結束。"
	textScreenshotHK  = "F8"
)
